language: java
jdk: oraclejdk8
sudo: false
script: 
- mvn com.blackducksoftware.integration:hub-maven-plugin:2.0.0:build-bom -Dhub.output.directory=. -Dhub.deploy.bdio=false
- bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./*_bdio.jsonld
